// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGAh27F70ZHKegUdjxnBBZ7dUMcOlkf6w',
    appId: '1:911833596616:web:a140360447909cc34d9bfd',
    messagingSenderId: '911833596616',
    projectId: 'venue-d65fd',
    authDomain: 'venue-d65fd.firebaseapp.com',
    storageBucket: 'venue-d65fd.appspot.com',
    measurementId: 'G-X1SN3EHJV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYdCdJkVoEetNGH5Nfh8VeR6n2hxMYObQ',
    appId: '1:911833596616:android:18153205015421d94d9bfd',
    messagingSenderId: '911833596616',
    projectId: 'venue-d65fd',
    storageBucket: 'venue-d65fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlVx1Ai_6zMA7k96EH-zpgiy-llIg_FOM',
    appId: '1:911833596616:ios:f40b8521b6054ca44d9bfd',
    messagingSenderId: '911833596616',
    projectId: 'venue-d65fd',
    storageBucket: 'venue-d65fd.appspot.com',
    iosClientId:
        '911833596616-j99g8bvj6lsqkpiqg9mi6e0bfl1akqfq.apps.googleusercontent.com',
    iosBundleId: 'net.redeemx.patron.venuestar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlVx1Ai_6zMA7k96EH-zpgiy-llIg_FOM',
    appId: '1:911833596616:ios:f40b8521b6054ca44d9bfd',
    messagingSenderId: '911833596616',
    projectId: 'venue-d65fd',
    storageBucket: 'venue-d65fd.appspot.com',
    iosClientId:
        '911833596616-j99g8bvj6lsqkpiqg9mi6e0bfl1akqfq.apps.googleusercontent.com',
    iosBundleId: 'net.redeemx.patron.venuestar',
  );
}
